# SPDX-License-Identifier: MPL-2.0

# The filter tests run a filter in a thread of their own, which they need to be
# able to observe the difference between ending one thread and ending all of
# them.
EXTRA_C_FLAGS := -static -lpthread

include ../../common/Makefile
